language: java
notifications:
  slack: mishima-group:8zsPeLEBTdLyT7kCZdQzIx4c
deploy:
  provider: heroku
  app: airportservice-tripbuddy
  api_key:
    secure: jWsvd2Ns4J/BNOlA4owK/HxnmUzP+PTIOGV5n68cxpi47FswQzCDQl8x4G6ixQnfgD7qcb8Gz+H7NQsBcJ4fTFWsZzO52fxbBsaDNuALjP//BAb6Kg1YqV7Bdx4h2HhLCwFewtGVYTYhcQ6771jbca8IpWUMK/Qq8Yu1g4ixtnoTAByjwABpwV1Aufx1/9hxY8C+LEfWkaaqEPcbfxl41jjb9k7pqF18KWgdvBX+PQceLXNrddjburd3+NboOiV3kWZRHUsRf5s7mUVhnqQO/f3JXhShWViwfJKGGlIhIKFABz5eEUT0yFjoAmTO4eDjCdi9ahjdYvI1/Oe9DcYD+5S4NkSo2oqffx7B863rPUONTbg6dgs3EfxSpX1KaKDpCmGQktTholipiC33CYfUY27Z24j6iAJuyd7LVcNIGKwabUNhDSQoJMYCd78GLsVulfOY7TOB2D0rE6WOyA15TdwLZvh5E2j49ktJknC0r8jBfBzCxotwCOQlfZdiLShhkOwwQPLkOJFF+plEe135xLPT2XDKIFlaPHkTgV5OVjXhhHJ/cOklsF9DRLZABfgm9ti7muxSpNlzVh98rBgxK36d1jVrsmgY/2GrfxB5wV8U7R0JcULkANWIIVVMjQs0zyERtl5wamvPbSqU2eaayp8fjfoL6ZSJnYVUlolpLbI=
